namespace BlazorStudio.ClassLib.Virtualize;

public record VirtualizeCoordinateSystemMessage(VirtualizeCoordinateSystemRequest? VirtualizeCoordinateSystemRequest,
    IVirtualizeCoordinateSystemResult? VirtualizeCoordinateSystemResult);