using BlazorStudio.ClassLib.FileSystem.Classes;

namespace BlazorStudio.ClassLib.Store.PlainTextEditorCase;

public record MemoryMappedFileReadRequestAction(PlainTextEditorKey PlainTextEditorKey, FileCoordinateGridRequest FileCoordinateGridRequest);